server:
  port: 10040
dubbo:
  application:
    name: yitao-auth-web
    qos-enable: false
  registry:
    address: zookeeper://192.168.3.220:2181?backup=192.168.3.221:2181,192.168.3.222:2181
spring:
  jackson:
    default-property-inclusion: non_null