spring:
  redis:
    host: 192.168.3.172
  rabbitmq:
    virtual-host: /
    username: test
    password: test
    host: 192.168.3.201
dubbo:
  application:
    name: yitao-auth-service
  protocol:
    port: 20885
  registry:
    address: zookeeper://192.168.3.220:2181?backup=192.168.3.221:2181,192.168.3.222:2181
server:
  port: 7781
yt:
  jwt:
    secret: yt@Login(Auth}*^778)&gerry%f35YUE2 # 登录校验的密钥
    pubKeyPath: D:/vip/keys/gerry/id_rsa.pub # 公钥地址
    priKeyPath: D:/vip/keys/gerry/id_rsa # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: YT_TOKEN
    cookieMaxAge: 1800
# 调用外部服务接口的前缀
client.url: http://api.yitao.com/