dubbo:
  application:
    name: yitao-upload-service
  protocol:
    port: 20881
    payload: 104857600
    name: hessian
  registry:
    address: zookeeper://192.168.3.220:2181?backup=192.168.3.221:2181,192.168.3.222:2181

yitao:
  upload:
    allowTypes:
    - image/jpeg
    - image/png
    - image/bmp
    baseUrl: http://yitao.image.com/
server:
  port: 7777