yt:
  jwt:
    pubKeyPath: D:/vip/keys/gerry/id_rsa.pub # 公钥地址
    cookieName: YT_TOKEN # cookie的名称
  filter:
    allowPaths:
    - /api/auth # 授权中心
    - /api/search # 商品搜索
    - /api/user/register #注册
    - /api/user/check # 检验数据类型
    - /api/user/send # 发送验证码
    - /api/user/query # 用户查询
    - /api/item # 商品页
    - /item # 商品详情