spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: DatebookHikariCP
    password: 123
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/orange?useSSL=false&serverTimezone=UTC
    username: root
dubbo:
  application:
    name: yitao-seller-service
  protocol:
    port: 20880
  registry:
    address: zookeeper://192.168.3.220:2181?backup=192.168.3.221:2181,192.168.3.222:2181
logging:
  level:
    com.gerry.yitao.mapper: debug
server:
  port: 5555